"""
Sources d'actualité alignées sur le cahier des charges (MA + international).
Champs métier : pays (country_code), région, langue — alimentent le DW (articles par pays).
"""
SOURCES = [
    {
        "name": "hespress",
        "url": "https://www.hespress.com/",
        "lang": "ar",
        "country_code": "MA",
        "region": "MA",
        "article_selector": "div.post-card",
        "title_sel": "h3.card-title a",
        "link_sel": "h3.card-title a",
        "date_sel": None,
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "akhbarona",
        "url": "https://www.akhbarona.com/",
        "lang": "ar",
        "country_code": "MA",
        "region": "MA",
        "article_selector": "div.card",
        "title_sel": ".card-body a",
        "link_sel": ".card-body a",
        "date_sel": None,
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "barlamane",
        "url": "https://barlamane.com/",
        "lang": "ar",
        "country_code": "MA",
        "region": "MA",
        "article_selector": "h2 > a",
        "flat_links": True,
        "date_sel": None,
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "lakom",
        "url": "https://lakom.ma/",
        "lang": "ar",
        "country_code": "MA",
        "region": "MA",
        "article_selector": "article h2 a",
        "flat_links": True,
        "date_sel": None,
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "aljazeera_ar",
        "url": "https://www.aljazeera.net/",
        "lang": "ar",
        "country_code": "QA",
        "region": "INTL",
        "article_selector": "article",
        "title_sel": "h3 a",
        "link_sel": "h3 a",
        "date_sel": "time",
        "author_sel": None,
        "category_sel": "span.article__tag",
    },
    {
        "name": "bbc_arabic",
        "url": "https://www.bbc.com/arabic",
        "lang": "ar",
        "country_code": "GB",
        "region": "INTL",
        "article_selector": "li[data-testid]",
        "title_sel": "h3",
        "link_sel": "a",
        "date_sel": "time",
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "cnn_world",
        "url": "https://edition.cnn.com/world",
        "lang": "en",
        "country_code": "US",
        "region": "INTL",
        "base_url": "https://edition.cnn.com",
        "article_selector": "li.card[data-component-name='card'] a.container__link",
        "flat_links": True,
        "date_sel": None,
        "author_sel": None,
        "category_sel": None,
    },
    {
        "name": "reuters",
        "url": "https://www.reuters.com/",
        "lang": "en",
        "country_code": "GB",
        "region": "INTL",
        "article_selector": "article",
        "title_sel": "a[data-testid='Heading']",
        "link_sel": "a[data-testid='Heading']",
        "date_sel": "time",
        "author_sel": None,
        "category_sel": None,
    },
]
